# Generated by Django 5.0.6 on 2024-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_post_remove_productimage_product_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
