# Generated by Django 5.0.6 on 2024-06-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_buyurtma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyurtma',
            old_name='nomi',
            new_name='ism',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='posts',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.buyurtma')),
            ],
        ),
    ]
