# Generated by Django 5.0.6 on 2024-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_rename_nomi_buyurtma_ism_rename_posts_orderitem_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='mahsulotlar',
            field=models.TextField(),
        ),
    ]
